### ISSUE TITLE
Error with confoundings Parameter in mainfeature() Function

### ISSUE THREAD

**Issue by aa20g217** [yuabrahamliu/methylClass#1]
Dear @yuabrahamliu ,

Thank you for developing this wonderful pipeline.

I am encountering an error when trying to use `mainfeature()` to select the top 10k probes using limma, specifically when using the `confoundings` and `anno` parameters to correct for EPIC and 450k versions.

**Error Details**

```
Error in limma::lmFit(dat, design) : 
  row dimension of design doesn't match column dimension of data object
```

**Command and Parameters**

Here is the command I am using:

```r
selProbes["limma"] = mainfeature(
  y.. = labels,
  betas.. = betas,
  subset.CpGs = "limma",
  padjcut = 0.05,
  xcutoff = 0.1,
  cutnum = 10000, # Number of probes to select
  confoundings = c("version"),
  anno = anno
)
```

**Data Dimensions**

- **Betas DataFrame Dimensions:**
```r
dim(betas)
# Output: [1] 252 227315
```

- **Annotation File Dimensions:**
```r
dim(anno)
# Output: [1] 252 3
```

**Sample Annotation File**

| label | sentrix | version |
|-------|---------|---------|
| A     | 1       | 450k    |
| B     | 2       | 450k    |
| B     | 3       | EPIC    |
| D     | 4       | 450k    |
| D     | 5       | 450k    |

**Request for Assistance**

I would appreciate any guidance or pointers you can provide to help resolve this issue.

Thank you in advance for your assistance.

Best regards,  
Akshay

**Comment by yuabrahamliu** [comment]
I don't know from the current information. Can you share an example dataset with me so that I can look into it?

**Comment by aa20g217** [comment]
Dear @yuabrahamliu,

Thank you for your prompt response. I have successfully resolved the previous issue.

I have a new question now. **How can we use `mainpredict()` when some of the probes used to train the model are missing in the `newdat` (test) dataset?**

Best regards,
Akshay

**Comment by yuabrahamliu** [comment]
The testing dataset will need to contain the complete features. However, in your case, I suggest using the `impute.knn` function in the `impute` package to fill in the missing values in your testing dataset, and then transfer it to `mainpredict`.
